[patch.crates-io]
#seedwing-policy-engine = { path = "../seedwing-policy/engine" }
seedwing-policy-engine = { git = "https://github.com/seedwing-io/seedwing-policy", rev = "bedbf11241fab341bff11302f727dc17e599af9e" }

[workspace]
members = [
    "common",
    "cli",
    "lsp-common",
]
exclude = [
    "lsp-wasi"
]
